#!/usr/bin/env php
<?php

/**
 * Castor Application Entry Point.
 */

// Import statements.
use Castor\Console\Application;

// Include composer's autoloader when local.
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
}

// Include composer's autoloader when global dependency.
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
}

// Creates a new Castor Application instance.
$castor = new Application();

// Run Barry, Run!
$castor->run();
